name: CI
on: [ push, pull_request ]

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: Psalm
                uses: docker://vimeo/psalm-github-actions
                with:
                    args: --shepherd
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                include:
                    -   php-versions: '8.1'
                        coverage: xdebug
                        composer-prefer: '--prefer-lowest --prefer-stable'
                        phpunit-flags: '--coverage-clover coverage.xml'
        steps:
            -   uses: actions/checkout@master

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: ${{ matrix.coverage }}

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ matrix.composer-prefer }}$-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-${{ matrix.composer-prefer }}-

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --ignore-platform-req="ext-*" ${{ matrix.composer-prefer }}

            -   name: Run test suite
                run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}

            -   name: Upload coverage
                uses: paambaati/codeclimate-action@v3.0.0
                if: matrix.coverage
                env:
                    CC_TEST_REPORTER_ID: <code_climate_reporter_id>
                with:
                    coverageCommand: vendor/bin/phpunit
                    debug: true
