name: "Code Style"

on:
    pull_request:
        paths:
            - "**.php"
            - "phpcs.xml.dist"
            - ".github/workflows/phpcs.yaml"
    push:
        paths:
            - "**.php"
            - "phpcs.xml.dist"
            - ".github/workflows/phpcs.yaml"

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # important!

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - uses: tinovyatkin/action-php-codesniffer@v1
              with:
                  files: "**.php" # you may customize glob as needed
                  phpcs_path: vendor/bin/phpcs
                  standard: phpcs.xml.dist
